sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.17.1

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - docker-compose version

script:
  - docker-compose build
  - docker-compose run app npm ci
  - docker-compose run app npm run compile
  - docker-compose run app npm run check
  - docker-compose run app npm run test
